### ISSUE TITLE
Issues with two providers and React Native Navigation (wix)

### ISSUE THREAD

**Issue by Omelyan** [kirillzyusko/react-native-keyboard-controller#130]
**Describe the bug**
Everything is fine with the first screen shown. We can receive keyboard events as usual. But as soon as the second screen pushed and then popped out, the first screen didn't receive any keyboard events anymore.
RNN needs declared providers for every screen. It seems that when two KeyboardProvider's are rendered with RNN the first one becomes unresponsive.
Reproducible in a clean project with the following requirements:

 - OS: Android 10 API 29 (with API 30+ everything works fine; in iOS it's ok too)
 - RN version: 0.71.2
 - RN architecture: old
 - RNN version: 7.32.1
 - JS engine: Hermes
 - Library version: 1.4.4

**Comment by kirillzyusko** [comment]
Hi @Omelyan 
Thank you for reporting the issue. Could you please create a small reproducible example? 👀

**Comment by Omelyan** [comment]
> Hi @Omelyan Thank you for reporting the issue. Could you please create a small reproducible example? 👀

Hi, yeap I did some tests and found how this can be solved. This is interesting...
https://github.com/Omelyan/RNNKeyboardController-Test

Here's the starting point:
[RNNKC1.webm](https://user-images.githubusercontent.com/18326050/227926309-63440975-9acd-49b3-86ab-e58fb2f243fd.webm)

Interestingly, when you set https://github.com/Omelyan/RNNKeyboardController-Test/blob/6a4b942737ce1803f0ded0e727f29d1416f68f31/index.js#L14 to false (RNN can wait for initial screen rendering before push animation), then the first keyboard event will be skipped, but the next ones will work:
[RNNKC2.webm](https://user-images.githubusercontent.com/18326050/227927013-1f98485e-d35b-4ca7-8791-659a408eaff4.webm)

And finally, when set navigationBarTranslucent for KeyboardProvider everything works fine:
[RNNKC3.webm](https://user-images.githubusercontent.com/18326050/227928412-e2426c42-ed97-42d8-85a5-f158b15ca032.webm)

**Comment by Omelyan** [comment]
> 

@kirillzyusko sadly, but it seems not all are so good :(
Check this video. While keyboard is shown, I push a new screen. Keyboard hiding on switching screens. Then on a new screen I focus input and keyboard showing again. But after closing current screen (keyboard hides) the first screen thinks that keyboard is still on. And the worst thing is that it happens from time to time, not always.
[RNNKC4.webm](https://user-images.githubusercontent.com/18326050/228019477-eaced99e-6389-4ddb-925f-c5095f4cb089.webm)

**Comment by Omelyan** [comment]
> Well, thank you @Omelyan for providing repro and describing all your findings. It's very helpful! I'm going to clone your repo and see what's going wrong with the app 👀

that's great, you're the most responsive lib main on my mind... And the lib is great and really helpful. I can think workarounds on this, and yeap I know that RN is not so popular and maybe the issue is on that side, but it will take to much if/else I guess.

**Comment by kirillzyusko** [comment]
What I've found today is:

1. The lifecycle methods `onStart`/`onProgress`/`onEnd` are not triggered because of this:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/22820318/228050393-4f66e64b-06f2-4d1c-97d6-4f27e263b64b.png">

For some reasons after going back `callback.mDispachedInsets` and `insets` are equal 🤷‍♂️ 

2. I've tried to re-create next example:

```tsx
/* eslint-disable react-native/no-inline-styles */
import React, {useState} from 'react';
import {
  Button,
  Keyboard,
  ScrollView,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import {
  KeyboardProvider,
  useKeyboardHandler,
} from 'react-native-keyboard-controller';
import {Navigation} from 'react-native-navigation';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';
import {SecondScreen} from './SecondScreen';

const FirstScreenA = ({componentId}) => {
  const y = useSharedValue(0);

  const style = useAnimatedStyle(() => ({
    height: withTiming(y.value),
  }));

  useKeyboardHandler({
    onStart(e) {
      'worklet';
      y.value = 40 * e.progress;
    },
  });

  return (
    <ScrollView
      style={{
        backgroundColor: 'blue',
      }}
      contentContainerStyle={{
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingVertical: 30,
      }}>
      <View
        style={{
          alignSelf: 'center',
          width: 70,
          aspectRatio: 0.6,
          borderWidth: 5,
          borderRadius: 10,
          marginBottom: 20,
          borderColor: 'white',
        }}>
        <Animated.View
          style={[
            {
              position: 'absolute',
              left: -1,
              right: -1,
              bottom: -1,
              backgroundColor: 'white',
            },
            style,
          ]}
        />
      </View>

      <View
        style={{
          height: 200,
          borderWidth: 10,
          marginBottom: 20,
          padding: 10,
          backgroundColor: 'yellow',
        }}>
        <TouchableOpacity
          style={{height: 50, backgroundColor: 'tomato'}}
          onPress={() => {
            Navigation.push(componentId, {
              component: {name: 'Second screen'},
            });
          }}
        />
      </View>

      <View
        style={{
          height: 200,
          borderWidth: 10,
          marginBottom: 20,
          backgroundColor: 'yellow',
        }}>
        <TextInput style={{height: 40, backgroundColor: 'white'}} />
      </View>

      <View
        style={{
          height: 200,
          borderWidth: 10,
          marginBottom: 20,
          backgroundColor: 'yellow',
        }}>
        <TextInput style={{height: 40, backgroundColor: 'white'}} />
      </View>
    </ScrollView>
  );
};

export const FirstScreen = ({componentId}) => {
  const [show, setShow] = useState(false);

  return (
    <View style={{flex: 1}}>
      <View style={{flex: 0.5}}>
        <KeyboardProvider>
          <FirstScreenA componentId={1} />
        </KeyboardProvider>
      </View>
      <View style={{flex: 0.5}}>
        <Button title="toggle" onPress={() => setShow(c => !c)} />
        {show && (
          <KeyboardProvider>
            <SecondScreen componentId={2} />
          </KeyboardProvider>
        )}
      </View>
    </View>
  );
};
```

To verify the idea that unmounting of `Provider` can cause unresponsiveness of first mounted provider. But the idea was wrong - everything works fine, i. e. that `react-native-navigation` also has an influence on this.

I'll continue my research tomorrow.

**Comment by Omelyan** [comment]
> it seems like I found a fix. We just need to remove callbacks when the view is detached from window and set new callback when view is attached again. I'm going to do more tests today at evening. If everything is okay then I'll open a PR and ask you to verify my changes, if you don't mind

sounds great, will be waiting, thanks

**Comment by kirillzyusko** [comment]
@Omelyan could you install a version from this branch: https://github.com/kirillzyusko/react-native-keyboard-controller/tree/fix/invalidate-callbacks-when-view-is-detached and verify whether it fixes the problem or not?

To be honestly I've discovered another problem and applied ugly fix that I don't like. Since I'm handling status/navigation bar paddings like in `onApplyWindowInsetsListener` -> this listener can be called many times and as a result if you open a second screen, then return back to a first one - happens too many calls to methods which are changing layout and as a result view is getting not laid out properly and first keyboard appearance is getting ignored. I've fixed the problem by calling `setPaddings` only one time 😅 But in my opinion such fix can break something else in the future, so in a meantime while you are testing I'll try to come up with a better fix.

**Comment by Omelyan** [comment]
> verify whether it fixes the problem or not?

unfortunately nothing seems changed :(
https://user-images.githubusercontent.com/18326050/228289248-5dc38acd-debf-438a-a7de-d514cd49bff3.mov

I updated git test project

**Comment by kirillzyusko** [comment]
@Omelyan thank, seems like I need to dive into the issue deeper 👍

**Comment by Omelyan** [comment]
@kirillzyusko btw, events are called several times for some reason on switching screens, while the keyboard is hidden all the time

**Comment by Omelyan** [comment]
@kirillzyusko Hello. One more thing noticed: screen resize events are fired, causing different layouts before and after the new screen is pushed:

https://user-images.githubusercontent.com/18326050/228472741-ec2394d8-23d7-4519-a9f6-682b6a73b56e.mov

**Comment by kirillzyusko** [comment]
Well, I think yes, there are many related things...
Yesterday I've tried to attach a single listener to `decorView` but even in this case the listener is also getting broken 🤯 
(Here is a patch in case if you are interested: [react-native-keyboard-controller+1.4.4.patch](https://github.com/kirillzyusko/react-native-keyboard-controller/files/11098635/react-native-keyboard-controller%2B1.4.4.patch))

@Omelyan maybe you have TG/Discord - we could have a conversation there and share all findings there in order to fix the issue faster 🙂 You can post your contact here (and the edit a message later in order not to share it for everyone) or send me a message on gmail if you want

**Comment by Omelyan** [comment]
@kirillzyusko good idea)
https://t.me/Omelyan
