### ISSUE TITLE
react-navigation/stack & android 10

### ISSUE THREAD

**Issue by odeyatwi** [kirillzyusko/react-native-keyboard-controller#235]
**Describe the bug**
in android 10 and below, when navigating using react-navigation/native, when going back the keyboard values and events stop responding.

in screen A everything is fine, when i go to screen B, everything is fine too, but when i go back to screen A (by using hardware back or navigation lib back) the animation and values stop updating in screen A.
when navigate to screen B or C, the new screen will respond correctly.

this happened only in android 10 and below, android 11+ work perfectly!

**Code snippet**

```
export default function KeyboardAnimation() {
  const { height, progress } = useKeyboardAnimation();
  const { height: heightReplica } = useKeyboardAnimationReplica();
  const navigation = useNavigation()

  return (
    <View style={styles.container}>
      <View>
       <Button onPress={()=>{
        navigation.navigate('REANIMATED_CHAT',{})
       }} title='PRESS ME'/>
        <Animated.View
          style={{
            width: 50,
            height: 50,
            backgroundColor: 'green',
            borderRadius: 25,
            transform: [
              {
                translateX: progress.interpolate({
                  inputRange: [0, 1],
                  outputRange: [0, 100],
                }),
              },
            ],
          }}
        />
      </View>
      <View>
        <TextInput
          style={{
            width: 200,
            marginTop: 50,
            height: 50,
            backgroundColor: 'yellow',
          }}
        />
        <View style={[styles.row, styles.center]}>
          <Animated.View
            style={{
              width: 50,
              height: 50,
              backgroundColor: 'red',
              borderRadius: 25,
              transform: [{ translateY: height }],
            }}
          />
          <Animated.View
            style={{
              width: 50,
              height: 50,
              backgroundColor: 'blue',
              borderRadius: 25,
              transform: [{ translateY: heightReplica }],
            }}
          />
        </View>
      </View>
    </View>
  );
}
```

**Repo for reproducing**
i don't have, add button in the example code, navigate from 'KeyboardAnimation' screen to 'ReanimatedChat' screen and go back

**To Reproduce**
1. add the upper code to KeyboardAnimation/index.tsx
2. Click on 1.AnimatedTransition
3. press on the new Button 'PRESS ME'
4. press back on the navigation header
5. open keyboard in screen

**Expected behavior**
the animations will act as they was when we open the screen for the first time

**Screenshots**
https://github.com/kirillzyusko/react-native-keyboard-controller/assets/31067303/ef0fcaa0-072b-40ee-862e-4deb595ac192

**Smartphone (please complete the following information):**
 - Desktop OS: MacOs m1 13.4.1
 - Device: samsung galaxy s9
 - OS: android 10
 - RN version: 0.72.4
 - RN architecture: old
 - JS engine: hermes
 - Library version: 1.7.0

**Comment by kirillzyusko** [comment]
Hello @odeyatwi 

Such effect happens because of default hooks [behavior](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/guides/building-own-hook). When you push screen `A` -> hook changes softInputMode to `resize`. When you push screen `B` -> it again changes softInputMode to `resize`. When screen `B` gets unmounted (when you go back to `A`) - it changes softInputMode back to default one (in example app it's `adjustPan`).

I strongly encourage you to read [this](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/guides/building-own-hook) guide and develop your own hook that will fit your app requirements (i. e. change softInputMode in such places where you need to track keyboard movement and return it back where you need your default behavior).

I've tested example app with your code and removed `return () => KeyboardController.setDefaultMode();` code - everything worked fine.

I'm going to close this issue, but feel free to re-open it if something is still unclear 😊
