### ISSUE TITLE
Expo Router + Tab, added padding and choppy initial start

### ISSUE THREAD

**Issue by MariuzM** [kirillzyusko/react-native-keyboard-controller#266]
Hi,
Im testing Expo Router with bottom tabs. I have noticed couple of things:
1. Once the keyboard is up it shows `blue` padding i guess this is because of tab height but wandering why is that? 
2. On the initial start i kinda feel that are skipped frames, there is bigger jump for showing the 

Slow mode video

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/36937039/ea1b56cb-7c6f-4806-9974-498e74ac8598

Normal speed

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/36937039/6b57f5b4-bcda-4769-8f86-3920537c075e

Repo
https://github.com/MariuzM/expo-starter/blob/chat/app/index.tsx

**Comment by MariuzM** [comment]
For now only way to get rid of padding is by doing, but not sure if this is the optimal solution
<img width="525" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/36937039/d44054e9-ceb8-4363-8ea6-d809b166cce5">

**Comment by kirillzyusko** [comment]
Thanks @MariuzM for providing a repro!

I'll try to have a look today evening 👍 

I haven't checked your code, but just wondering - where you've added this blue rectangle?

**Comment by MariuzM** [comment]
No problem, thank you. 
Its on the `<Animated.View style={fakeView} />` i should have just added as style prop instead of inside of `useAnimatedStyle` ive just been lazy :)

**Comment by kirillzyusko** [comment]
> Temp fix for android, had todo Platform for Android only because for iOS its also being detected but i don't need because useBottomTabBarHeight already has it.

@MariuzM I think it's the only one solution. You have a pretty complicated layout - not typical for other chat-like apps, where main text input is sticky to the bottom of the screen. Because of that you need to apply additional math.

Since your `TextInput` is above `TabBar` then you need to use `height - tabBar` formula to apply correct paddings.

And yes, on Android you need to add `insets.bottom`, because it seems like that value was already included in `useBottomTabBarHeight` value.

One small thing that I would recommend you is to use `useSafeAreaInsets` hook instead of `initialWindowMetrics`, just because `initialWindowMetrics` is a constant and it's not sensitive to changes of this value in runtime.

I'm going to close this issue since we've found a way how to calculate proper paddings for your case. Regarding choppy start problem - would you mind to open a new issue if the problem is still actual for you? I don't want to mix two different issues in a single issue (in future for other people it may simplify a search of old issues).
