### ISSUE TITLE
Differences from Reanimated's useAnimatedKeyboard

### ISSUE THREAD

**Issue by yayvery** [kirillzyusko/react-native-keyboard-controller#270]
Reanimated's [`useAnimatedKeyboard hook`](https://docs.swmansion.com/react-native-reanimated/docs/device/useAnimatedKeyboard/) appears to provide an equivalent API to keyboard-controller's `useReanimatedKeyboardAnimation`.

However, there are technical differences in the implementations:
- [`useReanimatedKeyboardAnimation`](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/reanimated.native.ts#L17) is implemented in React via Reanimated's `useEvent/useHandler` hooks using native events sent over the JS bridge.
- Reanimated's [`useAnimatedKeyboard`](https://github.com/software-mansion/react-native-reanimated/pull/3263/files#diff-b0e11ef9132ac168656a67901348fe300e4d449bcaabdfbc08500fb6576a7030R652) appears to update the shared values in C++, without ever going over the JS bridge.

Would there be a benefit for keyboard-controller to adopt a similar native implementation? Or even use Reanimated's `useAnimatedKeyboard` as the source of truth?

**Comment by kirillzyusko** [comment]
> Would there be a benefit for keyboard-controller to adopt a similar native implementation? Or even use Reanimated's useAnimatedKeyboard as the source of truth?

I don't think there would be any benefits, to be honest.

Indeed, I'm sending events via plain react events, but then I forward them to `Animated` value with `useNativeDriver: true` (which delivers a good performance) and if you are using [useReanimatedKeyboardAnimation](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/reanimated.native.ts#L17) then these events are intercepted on `useEvent/useHandler` level and dispatched synchronously on UI thread (the same mechanism is used for `ScrollView` - you can check `useAnimatedScrollHandler` implementation, they are doing exactly the same).

So right now I don't see a sense in usage C++ for delivering these events (however I have some other ideas where C++/JSI can be used within this library).

Last, but not least - if we compare the usage of 2 hooks, you can see, that from UI perspective they are working in the same way and you will not notice any difference on UI:


https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/be9df2d8-a1b1-4b9a-a176-5ffc9575f414

Did I answer your question?

**Comment by yayvery** [comment]
> Did I answer your question?

Yes! thank you for including the comparison :)

I will see if I can get clarity from Reanimated team on why they opted for that approach

Also very curious what uses of C++/JSI you have in mind, if you're ready to share!

**Comment by kirillzyusko** [comment]
> I will see if I can get clarity from Reanimated team on why they opted for that approach

@yayvery In my setup it requires an additional view (`KeyboardProvider`) to manage these events. Since they are using C++/JSI they can propagate these events to JS directly without a need to have a custom view (and do that synchronously of course).

I think that's all the difference 🙃 But in terms of performance two implementations are mostly the same (or at least you will not find a difference if you just see UI) 🙂 

> Also very curious what uses of C++/JSI you have in mind, if you're ready to share!

Yes, sure, it's not a secret 😉 

Basically that's the ideas that I have a t the moment:

1. I was thinking about creating an `interpolator` as a JSI function (right now you have pre-defined functions written natively, such as `linear`/`ios` for interpolator for `KeyboardGestureArea` view, but with worklets/JSI you could define custom interpolator and use your imagination for defining a transition 👀).

2. Another thing that I'm thinking to add is an `update` method for `useReanimtedFocusedInput` hook, so the signature will be like:

```ts
const {input, update} = useReanimatedFocusedInput();
```

The idea to have an ability to get a layout of text input on demand. I've tried to do some experiments with dispatching synchronous commands to a view (with REA api), and it works, but if I'm dispatching events from a native thread, then I get result only in next frame (and I think such delay is not desirable, so it's a potential place where JSI/C++ may come to the game).

**Comment by kirillzyusko** [comment]
@yayvery I'm going to close this issue. If you have any other questions - don't hesitate to ask them and open new issues 😎

**Comment by arunabhverma** [comment]
The reason I chose this library (and the difference from reanimated) is that it is also compatible with scenarios where the keyboard changes size, for example.

### Using Reanimated.
![test_1](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/59590144/06b027cc-d647-4f20-a48f-2197924d71c1)

### Using Keyboard Controller Lib
![test_2](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/59590144/782ce65b-25a6-444c-9aa4-9f7a743aa6be)

**Comment by arunabhverma** [comment]
The reason I chose this library (and the difference from reanimated) is that it is also compatible with scenarios where the keyboard changes size, for example.

### Reanimated example

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/59590144/60aae03c-a7b1-444f-9b08-09f97be8b929

### Keyboard Controller example

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/59590144/464a943b-f69a-4dac-9331-0e80f06d276f
