### ISSUE TITLE
Keeping single/multiline focused input in visible area while user is typing on iOS/Android

### ISSUE THREAD

**Issue by VladyslavMartynov10** [kirillzyusko/react-native-keyboard-controller#281]
The main goal of this feature is to enhance the behavior for users who are accustomed to automatically focused inputs in their native application. Since this library is the best cross-platform implementation for keyboard handling, it would be great to have such functionality out of the box.

After some research, we found out that iOS native implementation doesn't have this feature, so you have to play with native TextFields manually for achieving it. On the other hand, Android supports it without any extra manipulation.

In the current code examples, the most suitable place where we can implement this is within the KeyboardAwareScrollView. One way to achieve this autoscroll behavior is to calculate somehow if the current target is under the keyboard and then scroll to the focused input. We can extend this method using the React useImperativeHandle hook and then connect it to KeyboardAwareScrollView, but I'm not sure if it will work well without any performance loss.

**Comment by kirillzyusko** [comment]
Hello @VladyslavMartynov10 👋 

Good question!

Actually autoscroll happens on iOS (when you type first letter, because iOS is emitting `keyboardWillShow`/`keyboardDidShow` events and we call `maybeScroll` function): https://github.com/kirillzyusko/react-native-keyboard-controller/blob/5c587ca331eedb4b906e21d9774226b6294b0aad/example/src/components/AwareScrollView/KeyboardAwareScrollView.tsx#L87-L102

If you again scroll your focused input to invisible area and type another symbol - input will remain invisible (because no new `keyboardWillShow`/`keyboardDidShow` events will be emitted).

I was thinkning on how to create a cross-platform solution and right now I'm thinking about enhancing `useReanimatedFocusedInput` hook. I want to change a signature to be:

```tsx
const {input} = useReanimatedFocusedInput({
  onChangeText: (text) => {
    // we can call our internal `maybeScroll` on every text change
    // in native code before this event we need to assure that `layout` has up-to-date value
    // so we can call `maybeScroll` and it'll assure, that focused TextInput remains visible even
    // if user intentionally moved it out of visible area
  },
});
```

Also I think that such behavior can be activated on `KeyboardAwareScrollView` level via prop like `keepVisibleWhileTyping`.

What do you think about this approach?

**Comment by VladyslavMartynov10** [comment]
Yeah, I just forgot that now library is using  `useReanimatedFocusedInput` hook which can give us all necessary layout/focus information. I think the approach you proposed is the most appropriate here and easily extendable in the future.

**Comment by kirillzyusko** [comment]
@VladyslavMartynov10 I think the reason why it doesn't work now is because this condition:

```js
if (focusWasChanged && !keyboardWillAppear) {
```

 is evaluated as

```js
if (false && true) {
```

And `maybeScroll` is not getting called. Which is kind of good, because we have cross-platform code that works in identical way on both platforms iOS/Android - and if we add additional `scroll-on-text-change` logic, then we can be sure there is no other conflicts with remaining code 😎 

I'll try to enhance the functionality of `useReanimatedFocusedInput` to achieve the behavior you described 👍

**Comment by kirillzyusko** [comment]
Thank you @VladyslavMartynov10 for raising that problem and for your sponsoring! I appreciate that!

I've added the requested functionality and updated `KeyboardAwareScrollView` example.

I'm going to roll out a new release 1.10.0 soon (hopefully before a New Year 😅) and include `KeyboardAwareScrollView` as a pre-built component available out-of-box from this library.

But if you need these changes ASAP then you can use a version from `main` branch :)

**Comment by VladyslavMartynov10** [comment]
Thanks @kirillzyusko, great work! I'll write back some feedback after several testing.
