### ISSUE TITLE
Jest mock doesn't include newly exported KeyboardAwareScrollView

### ISSUE THREAD

**Issue by bcgilliom** [kirillzyusko/react-native-keyboard-controller#319]
**Describe the bug**

tests fail when `KeyboardAwareScrollView` is used in tests using the following from the docs

```
jest.mock("react-native-keyboard-controller", () =>
  require("react-native-keyboard-controller/jest"),
);
```

Adding something like:

```
export const KeyboardAwareScrollView = (props) => <ScrollView {...props} />;
```

to the mocks seems to work

**To Reproduce**

1. Add a test for a component that uses KASV
2. Run tests
3. see error about no being linked

**Expected behavior**
tests should run using the OOTB config

**Screenshots**
N/A

**Smartphone (please complete the following information):**

- Desktop OS: Mac
- Device: jest

**Comment by kirillzyusko** [comment]
Thanks @bcgilliom 

I will have a look on it over weekend (actually I think I mocked all low level hooks/views, and `KeyboardAwareScrollView` just consumes them, so **theoretically** it should work, but I haven't tested it).

And yes, thank you for raising this issue 🙏

**Comment by kirillzyusko** [comment]
@bcgilliom may I kindly ask you to check/review PR https://github.com/kirillzyusko/react-native-keyboard-controller/pull/320?

I've added `View` as a mock for `KeyboardAvoidingView` and `KeyboardStickyView` and added `ScrollView` as a mock for `KeyboardAwareScrollView`. But I don't know whether it's a good practice, because in snapshot testing non-view props (such as `behavior` for `KeyboardAvoidingView`) will be added to snapshot.

From one point it's good, because if someone accidentally changes it -> unit tests will fail, but I've tried to use default `KeyboardAvoidingView` and it's not including custom props into snapshot (Because a real implementation of `KeyboardAvoidingView` is used)
