### ISSUE TITLE
Weird Scroll when change text event fires on android 9 and 10

### ISSUE THREAD

**Issue by taha200** [kirillzyusko/react-native-keyboard-controller#384]
I started to use this library because it has great feature to avail and maintain time to time, I encountered the issue that I am experiencing the weird scroll whenever I write a text in my text input and it is happening on the android OS 9 and 10

`  <KeyboardAwareScrollView
      contentContainerStyle={{ flexGrow: 1, backgroundColor: 'white' }}
      keyboardShouldPersistTaps={Platform.OS === 'ios' ? 'never' : 'always'}
      bounces={false}
    >
<TextInput />
</KeyboardAwareScrollView>`

Video Link:
[https://wetransfer.com/downloads/2143ff1a64e1667cdb40042ba656fd4a20240312101324/dbc0bc](url)

**Comment by kirillzyusko** [comment]
Hey @taha200 

Can you provide more information please, especially:
- what are device manufacture? Can you give full spec like "Xiaomi Redmi Note 5 Pro Android 9"?
- what is the library version?
- can you paste here a minimal reproduction demo?
- is the problem reproducible in emulator?
- does the problem happens on Android 11+?

Most likely problem happens here - https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/components/KeyboardAwareScrollView/index.tsx#L197

You can try to comment out this line and see how it behaves. However for me it looks like there is a problem with memoization and it reads old layout from `TextInput` 👀

**Comment by kirillzyusko** [comment]
@taha200 I can not reproduce this problem in example app (I've tested app on Pixel 6 Pro, API 28):

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/5a570ba4-70e1-477b-95a3-dc3389ae6f10

Can you provide a minimal reproduction example, please?

**Comment by taha200** [comment]
Let me know the library version please?

**Comment by taha200** [comment]
I checked the same simulator and not getting this issue, but can you check on the physical device?

**Comment by kirillzyusko** [comment]
> Let me know the library version please?

This is example app from `main` branch (version 1.11.3).

> I checked the same simulator and not getting this issue, but can you check on the physical device?

I tested on a physical Xiaomi Redmi Note 5 Pro (Android 9) and Pixel 7 Pro (Android 14) and the issue is not reproducible. You've said it's reproducible on emulator - can you give me your emulator configuration?

**Comment by taha200** [comment]
I think I should upgrade the library version, I will check it and let you know
My bad I had mistakenly wrote yes for the emulator.

**Comment by taha200** [comment]
This issue is still persist in new version, can you help me out please?

**Comment by taha200** [comment]
I think the onchangetext with usememo as you stated earlier is making the problems, I am getting the problem in 9 and 10 all devices. @kirillzyusko

**Comment by taha200** [comment]
I used text input from react native paper

**Comment by kirillzyusko** [comment]
@taha200 I'd like to help you, but without a proper reproduction example I can't. Please, provide minimal reproduction example and ideally the problem should be reproducible in environment that we both can have (i. e. Android Studio/Genymotion emulator - I can try to run example in device farm, but minimal available version there is Android 11).

You can also try to debug this problem yourself. Two suspicious things are:
- usage of `onChangeText` here https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/components/KeyboardAwareScrollView/index.tsx#L209
- usage of `useSmoothKeyboardHandler` because it has its own interpolation on Android < 11 and doesn't listen to all keyboard events on these OS versions https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/components/KeyboardAwareScrollView/index.tsx#L214

**Comment by kirillzyusko** [comment]
Posting for better visibility - tried to find Samsung A01 on AWS device farm but didn't find it there 😔
