### ISSUE TITLE
using  StatusBar.setTranslucent with the keyboardProvider 

### ISSUE THREAD

**Issue by AbdulkarimTaha** [kirillzyusko/react-native-keyboard-controller#526]
Hi there , 
I previously had the ability to use StatusBar.setTranslucent or the StatusBar component on different pages to change the behavior of the status bar. However, when using the KeyboardProvider, I seem to have lost this ability. Now, I can only specify it in the <KeyboardProvider statusBarTranslucent={true}>. Even if I try to use StatusBar.setTranslucent(false) later, it does not change anything.

Is there a way to dynamically change the statusBarTranslucent property after initializing the KeyboardProvider?

**Comment by kirillzyusko** [comment]
Thank you for the issue @AbdulkarimTaha 

It happen because of: https://github.com/kirillzyusko/react-native-keyboard-controller/blob/08efc819fcc6ae09dfb857b2ba6ee9bf17fa10d1/android/src/main/java/com/reactnativekeyboardcontroller/modules/StatusBarManagerCompatModuleImpl.kt#L55-L65

May I ask you to show a video (without KeyboardProvider) how transition in your app between translucent/non-translucent status bar looks like?

This is a "known" bug in the library - I just want to see a video confirmation, that there is indeed a use-case in a real world app (that uses both modes) 👀
