### ISSUE TITLE
Using a KeyboardAwareScrollView above a FlatList makes for incorrect scrolling behavior

### ISSUE THREAD

**Issue by pavel-roj** [kirillzyusko/react-native-keyboard-controller#565]
**Describe the bug**
Putting a KeyboardAwareScrollView above a FlatList results in incorrect scrolling behavior when clicking on the TextInput contained within the FlatList. The KeyboardAwareScrollView only scrolls in such a way that the TextInput is visible on the screen but it is still hidden under the keyboard.

**Code snippet**

Render this on the screen:
```
return (
        <KeyboardAwareScrollView>
            <Text style={{ color: 'black', fontSize: 50 }}>Header</Text>
            <FlatList
                data={[1, 2, 3, 4, 5, 6, 7, 8]}
                scrollEnabled={false}
                renderItem={({ item }) => (
                    <View style={{ height: 200 }} key={item}>
                        <TextInput style={{ width: '100%', height: '100%', backgroundColor: '#bdaeff' }} />
                    </View>
                )}
                contentContainerStyle={{
                    gap: 50,
                }}
            />

            <Text style={{ color: 'black', fontSize: 50 }}>More Content</Text>
            <Text style={{ color: 'black', fontSize: 50 }}>...</Text>
            <Text style={{ color: 'black', fontSize: 50 }}>...</Text>
        </KeyboardAwareScrollView>
    );

```

**To Reproduce**

1. Create a component with a KeyboardAwareScrollView that wraps a FlatList
2. Add a TextInput component into the renderItem method of that FlatList
3. Click any of the text inputs
4. TextInput is hidden under the keyboard

**Expected behavior**
The TextInput should not be hidden under the keyboard. The example with the FlatList should work in the same way the following snippet does:

```
<KeyboardAwareScrollView>
    <Text style={{ color: 'black', fontSize: 50 }}>Header</Text>

    <View style={{ gap: 50 }}>
        {[1, 2, 3, 4, 5, 6, 7, 8].map((item) => (
            <View style={{ height: 200 }} key={item}>
                <TextInput style={{ width: '100%', height: '100%', backgroundColor: '#bdaeff' }} />
            </View>
        ))}
    </View>

    <Text style={{ color: 'black', fontSize: 50 }}>More Content</Text>
    <Text style={{ color: 'black', fontSize: 50 }}>...</Text>
    <Text style={{ color: 'black', fontSize: 50 }}>...</Text>
</KeyboardAwareScrollView>
```

**Additional context**
I don't want to use renderScrollComponent on the flat list as I need a "global" ScrollView that wraps the entire screen. The additional text in the snippet with More Content and ... is there to demonstrate that the screen contains more than just the list.

Thank you :heart:

**Comment by kirillzyusko** [comment]
@pavel-roj can you stick with `renderScrollComponent` approach and use plain `ScrollView` for your container? 🤔 

So the structure can be as:

```tsx
<ScrollView>
  <Text style={{ color: 'black', fontSize: 50 }}>Header</Text>
  <FlatList
    data={[1, 2, 3, 4, 5, 6, 7, 8]}
    scrollEnabled={false}
    renderItem={({ item }) => (
        <View style={{ height: 200 }} key={item}>
            <TextInput style={{ width: '100%', height: '100%', backgroundColor: '#bdaeff' }} />
        </View>
    )}
    renderScrollComponent={() => <KeyboardAwareScrollView {...props} />}
    contentContainerStyle={{
        gap: 50,
    }}
  />
  
  <Text style={{ color: 'black', fontSize: 50 }}>More Content</Text>
  <Text style={{ color: 'black', fontSize: 50 }}>...</Text>
  <Text style={{ color: 'black', fontSize: 50 }}>...</Text>
</ScrollView>
```

I think it's also highly recommended not to nest two scrollalbles with the same direction into each other (especially FlatList into ScrollView because it can break virtualization). Have you tried to use [ListHeaderComponent](https://reactnative.dev/docs/flatlist#listheadercomponent) and [ListFooterComponent](https://reactnative.dev/docs/flatlist#listfootercomponent)?

**Comment by pavel-roj** [comment]
@kirillzyusko Thank you for the quick reply. Using a plain <ScrollView> results in the same behaviour.

> Have you tried to use [ListHeaderComponent](https://reactnative.dev/docs/flatlist#listheadercomponent) and [ListFooterComponent](https://reactnative.dev/docs/flatlist#listfootercomponent)?

Since my screen is simpler it would be possible with some work to rework the screen into a single flat list with Header and Footer components and this would solve the issue, although I'm still worried that in the future I might encounter the same problem on more complex screens.

> I think it's also highly recommended not to nest two scrollalbles with the same direction into each other (especially FlatList into ScrollView because it can break virtualization).

I think it's okay to nest a FlatList/VirtualizedList in a ScrollView as long as the scroll on the nested component is disabled.


---

I currently have a custom hook that measures the positions of the rendered items relative to the "global" scroll component and scrolls onto them on focus of the input elements, which works okay, although the current calculations don't take into account the keyboard size fully.

I'm not sure if you want to support this scenario in the library itself. Using a flat list with a renderScrollComponent works well for simpler screens and more complex screens might require custom hooks.

**Comment by kirillzyusko** [comment]
>  as long as the scroll on the nested component is disabled

Ah, I didn't notice that! Basically that's the circle-pit 😅  `keyboard-controller` checks nearest scroll view and returns its tag.

Then in JS I compare, that input belongs to a particular view that needs to be scrolled: https://github.com/kirillzyusko/react-native-keyboard-controller/blob/6a2332b4ee18f6b1de8584f13d12eab39f7e5188/src/components/KeyboardAwareScrollView/index.tsx#L142-L145

It was made to optimize the code and don't scroll all ScrollViews on all previous screens. But in your case we return a `scrollViewId` that belongs to `FlatList` and thus `KeybaordAwareScrollView` doesn't do anything (because it thinks that it's a responsibility of other ScrollView to be scrollable).

> Using a plain <ScrollView> results in the same behaviour.

In this case I think `KeyboardAwareScrollView` sends command to scroll, but since it's disabled it just can't scroll itself because of that restriction 🙈 

I'll try to use your code and see whether I can reproduce the bug or not. The solution in my head is to check, that nearest `ScrollView` is not disabled - if it's disabled then continue traverse further 🤷‍♂️

**Comment by kirillzyusko** [comment]
@pavel-roj can you check if https://github.com/kirillzyusko/react-native-keyboard-controller/pull/566 fixes the problem?

**Comment by pavel-roj** [comment]
@kirillzyusko Yes, the fix does work! I can only test android right now, so I don't know if iOS is fixed as well, but android is fine now.


For anyone who might stumble upon this later: with the fix applied you can use the original component structure.
```
<KeyboardAwareScrollView>
    <FlatList scrollEnabled={false} />
</KeyboardAwareScrollView>
```

**Comment by kirillzyusko** [comment]
@pavel-roj nice, thank you! I think I'll publish a new version closer to Friday (want to wait for new tickets to come in and the publish everything together).

In a meantime you can use `patch-package` and apply necessary changes! Thank you for opening the issue and quick responses 😊
