### ISSUE TITLE
Unable to get the Keyboard controller to work in iPhone with multiple inputs

### ISSUE THREAD

**Issue by franferns** [kirillzyusko/react-native-keyboard-controller#574]
**Describe the bug**
Unable to get the Keyboard controller to work when run on ios simulator or iphone

**Code snippet**
![image](https://github.com/user-attachments/assets/a685289e-7879-4b0a-a44a-776dd8a34275)

**Repo for reproducing**
[Sample expo app.](https://github.com/franferns/expo-keyboard)

**To Reproduce**
1.Open the my-app 
2. tap on the green textbox or the red textbox keyboard pop ups and the input is hidden

**Expected behavior**
When clicked on the textbox which is Red or Green the the keyboard should push those inputs up . Have not been able to get this working . I have tried with the exact code given at the expo site 

**Screenshots**
https://github.com/user-attachments/assets/9033b2ae-c60b-4485-9cbf-f57d13faba94

**Smartphone (please complete the following information):**
-iPhone 15 / iPhone 15 Simulator

**Comment by kirillzyusko** [comment]
@franferns I think it happens only in latest version (1.13.x) because I re-worked the way how listeners are attached. And in new flow there could be a case when view is not mounted yet, but we are trying to attach a listener. Thank you for a detailed repo - I'll fix this bug next week. ❤️ 

And in a meantime you can try to use `1.12.x` - that issue shouldn't be present in this version 👀

**Comment by kirillzyusko** [comment]
@franferns I fixed a problem in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/575

May I ask you to test these changes and confirm whether it fixes a problem or not? 👀

**Comment by kirillzyusko** [comment]
@franferns My pleasure 😊
