### ISSUE TITLE
Know the KeyboardToolbar height

### ISSUE THREAD

**Issue by CorentinAndre** [kirillzyusko/react-native-keyboard-controller#601]
Hey 👋 first of all thanks for this lib, it's solving a lot of problems.

**Is your feature request related to a problem? Please describe.**
I'm using the KeyboardToolbar component and it works great. I often find myself wanting to space the input with the keyboard while taking into account the toolbar height. I know it's 42 because i measured it so I've included something like`bottomSpace = actualOffset + TOOLBAR_HEIGHT` and use it in my component. 

**Describe the solution you'd like**
I feel like this should be provided by the lib though. One way of doing it would be to allow to forward props to the root view. This way we can write
 ```Typescript <KeyboardToolbar onLayout={handleLayout} />```
We can retrieve the height directly in the onLayout event. What do you think of this ?
Do you have a better idea ? I can definitely make the implementation changes if it's ok for you.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by kirillzyusko** [comment]
Hey @CorentinAndre 

The current height is hardcoded and the size is `42`. However I think that your suggestion with `onLayout` absolutely makes sense! You as a developer shouldn't rely on constants that are not exposed from this package directly because they can be changed at any time. And `onLayout` callback seems to be a good choice 😊

The only thing I'm thinking of is the fact, that apart of `onLayout` people may want to use other props (accessibility-related or any other, such as collapsible, nativeID, etc.) 🤔

So maybe it would make sense to grab remaining props in `rest` property and pass it to the container view? What do you think?

That would be amazing if you could submit a PR 🙏

**Comment by CorentinAndre** [comment]
In fact I thought about this after sending the issue and tried spreading the props, it works quite great 🙈 I'll make a PR, thanks a lot

**Comment by kirillzyusko** [comment]
Thank you @CorentinAndre ❤️
