### ISSUE TITLE
Blank space beneath KeyboardToolbar after switching from emoji to text keyboard

### ISSUE THREAD

**Issue by RobertPetricevic** [kirillzyusko/react-native-keyboard-controller#622]
**Describe the bug**
On clicking input field, keyboard and keyboard toolbar is working fine. If I switch to emoji keyboard and then come back, there is blank space between keyboard and toolbar.

**Code snippet**
```
import React from 'react';
import { TextInput } from 'react-native';
import {
  KeyboardAwareScrollView,
  KeyboardToolbar,
} from 'react-native-keyboard-controller';

const Test = () => {
  return (
    <>
      <KeyboardAwareScrollView>
        <TextInput
          style={{
            height: 40,
            marginTop: 300,
            marginBottom: 50,
            borderColor: 'gray',
            borderWidth: 1,
          }}
        />
        <TextInput
          style={{
            height: 40,
            marginBottom: 50,
            borderColor: 'gray',
            borderWidth: 1,
          }}
        />
      </KeyboardAwareScrollView>
      <KeyboardToolbar />
    </>
  );
};

export default Test;
```

**Smartphone (please complete the following information):**

Device:
- simulator iPhone 15 Pro Max- iOS 17.5
- device iPhone Xs - iOS 18.0

Libraries:
- "expo": "^51.0.32"
- "react-native": "0.74.5"
- "react-native-keyboard-controller": "^1.13.3"

**Comment by kirillzyusko** [comment]
https://github.com/user-attachments/assets/01a6d845-2dcb-4693-8f2c-a90f9f915190

@RobertPetricevic I just tested and it works fine. Would you mind to elaborate a little bit more on:
- which device you are using (is it real or not)? As I can understand the problem is reproducible on simulator as well?
- is it reproducible in debug build?
- can you attach a video showing a problem?
- can you provide a reproduction example?
- can you verify whether the problem is reproducible on latest 1.14.0 release?

**Comment by RobertPetricevic** [comment]
@kirillzyusko, sorry I erased half of my content and video when I was pasting the code.

1. Yes is it reproducible on mentioned devices, physical iPhone xs and simulator iPhone 15
2. This video is recorded in development, but the same is on production
3. Here is the video
https://github.com/user-attachments/assets/5c35d0b7-1eec-4112-ae02-33944adf16af 
4. I cant provide repro now, but I will as soon as I get home
5. problem is reproducible on latest release

**Comment by kirillzyusko** [comment]
Thank you @RobertPetricevic 🙌 

The video definitely looks strange. I can recommend you to try to 1.12.x version or even 1.11.x, but I think all of them will have the same problem 🤷‍♂️ 

Curious to see repo configuration and try to reproduce it on my end!

**Comment by kirillzyusko** [comment]
@RobertPetricevic have you tried to reproduce this problem in isolated environment? 👀

**Comment by RobertPetricevic** [comment]
@kirillzyusko uhhh hi sorry

I'll try it by the end of the week for sure, don't close issue yet :)

**Comment by kirillzyusko** [comment]
> I'll try it by the end of the week for sure, don't close issue yet :)

Okay, sure 🙌

**Comment by RobertPetricevic** [comment]
I can't even reproduce my issue cause I'm stuck on this: 
<img width="366" alt="image" src="https://github.com/user-attachments/assets/bc25669f-a29d-4678-93e8-f1d8e27f9fbf">


Why do I have this gap between toolbar and keyboard..... I have the simplest example
<img width="371" alt="image" src="https://github.com/user-attachments/assets/bb6a0b75-6975-464f-9555-a958fd02dd79">

**Comment by kirillzyusko** [comment]
@RobertPetricevic can you share a full code sample (including styles)? Do you see a toolbar when keyboard is closed?

You can adjust the space between `KeyboardToolbar` and the keyboard via `offset` property, but I don't understand why your space is such a big one...

**Comment by RobertPetricevic** [comment]
@kirillzyusko here is the repo: https://github.com/RobertPetricevic/rnkc-test

sorry I'm slow again.... 

 I don't see the toolbar when keyboard is closed

**Comment by RobertPetricevic** [comment]
@kirillzyusko hi, so this new prop should be in the next release right?

**Comment by kirillzyusko** [comment]
Yes @RobertPetricevic 😀

Hopefully I can drop 1.15.0 soon (maybe in 1-2 weeks)

**Comment by RobertPetricevic** [comment]
great @kirillzyusko 

thanks for effort, quick responses and of course, for this library 😊

**Comment by RobertPetricevic** [comment]
Hi @kirillzyusko, this gap between the toolbar and keyboard, as well as my initial bug, is now fixed with the use of "offset" props, thanks once more :)

I'll add a comment here with two more questions, and later, if you want, I can open an issue for them. If it turns out they are really bugs connected to this library, the course

So, let's begin with the one that is not a bug of this library for sure, but I would like to ask your opinion on this. I have initialized new project without your library and the bug is still there.
If I have two inputs that have the "secureEntry" prop, focusing on the first one will have a small but noticeable delay.

https://github.com/user-attachments/assets/85cb9002-a9e6-404d-8d93-b9df098f1e0b


The second bug is this: if on both screens in the stack navigator I have KeyboardToolbar, on going back, I will, in the background, have a toolbar that is being dismissed as navigating back. I'm not sure what am I doing wrong.

https://github.com/user-attachments/assets/e1b75b40-4908-4370-a5b4-2efb0aa54572


There's no much additional code, I just have a commit in which I have added secureEntry props

**Comment by kirillzyusko** [comment]
> The second bug is this: if on both screens in the stack navigator I have KeyboardToolbar, on going back, I will, in the background, have a toolbar that is being dismissed as navigating back. I'm not sure what am I doing wrong.

It's definitely a bug. It basically happens because I animate two `KeyboardToolbar`s at the same time... Me (as a library author) can not distinguish which toolbar is shown on the screen at the moment. Potentially I can add a new property `enabled` (similar to `KeyboardAvoidingView` and `KeyboardAwareScrollView` components) and you can use it like:

```tsx
const isFocused = useIsFocused();

<KeyboardToolbar enabled={isFocused} />
```

In this case we'll animate only view that currently visible on the screen (it'll also improve performance a little bit, since we'll animate only one element instead of N-elements). Please, create an issue for that and I'll add a new prop (or if you want you can add this property yourself and open a PR).

<hr>

Regarding second bug - does it happen only if you switch focus from `Input 1` to `Input 2`? i don't see a delay when you switch between `input 1` and `input 3` 🤔 It looks like only `input 2` slow things down, right?

**Comment by RobertPetricevic** [comment]
@kirillzyusko quick again :)

okay I get it, I'll open a separate issue thanks :)

for the second bug - yes delay is visible when I switch focus from `Input 1` to `Input 2` or  from `Input 3` to `Input 2`. 
When focus is switched between `Input 1` and `Input 3`, and vice versa, there is no delay

**Comment by kirillzyusko** [comment]
> When focus is switched between Input 1 and Input 3, and vice versa, there is no delay

Got it

Well, I can not recommend anything - I don't know why such delay happens 🤔 I think I saw such delays in example app as well, but as you said earlier - if it's reproducible without keyboard-controller, then it means that the problem is somewhere in react-native itself.

You can try to profile the app using XCode tools - maybe they can give any insights into what's going wrong. Or open an issue in react-native repository 🙂

**Comment by RobertPetricevic** [comment]
Yes, it is definitely something with the react-native itself. Thanks once more @kirillzyusko
