### ISSUE TITLE
Version 1.9.x failing

### ISSUE THREAD

**Issue by rarenatoe** [kirillzyusko/react-native-keyboard-controller#643]
**Describe the bug**
I decided to install the latest compatible version of react-native-keyboard-controller on my react-native 0.72 project.
I got the following error message when running it on iOS:
```
Exception thrown while executing UI block: -
[react_native_keyboard_controller.KeyboardControllerView setOnFocusedInputLayoutChanged:]: unrecognized selector sent to instance 0x7f9e45d1c7d0
```
Versions 1.6.x-1.8.0 work fine.

**To Reproduce**

3. Use `KeyboardProvider` at the highest level component as indicated in the setup.
4. Build and Run on iOS.
5. When the build succeeds and all elements have been loaded, the exception shows as a red/black screen.

**Expected behavior**
Should work fine since the compatibility table says react-native-keyboard-controller works on 1.60+ for react-native 0.72

**Screenshots**
![Screenshot 2024-10-16 at 4 36 51 PM](https://github.com/user-attachments/assets/78f922ee-d03f-4068-afce-0060b707a278)

**Smartphone (please complete the following information):**

- Desktop OS: macOS 14
- Device: iPhone 15 Simulator
- OS: iOS 15
- RN version: 0.72
- RN architecture: fabric
- JS engine: Hermes
- Library version: 1.9.x

**Comment by kirillzyusko** [comment]
@rarenatoe interesting! 1.9.x brought new functionality, such as focused input tracking (layout). And it looks like events can not pass from native to JS because there is no corresponding callback.

However I tested code on both fabric/paper and 1.9.x was working everywhere just fine 🤷‍♂️ You can check source code at https://github.com/kirillzyusko/react-native-keyboard-controller/tree/1.9.5

May I ask you to provide a reproduction code so that I can have a look on it and see how it can be fixed?

**Comment by rarenatoe** [comment]
Hey, thanks for the fast response! Some time later I tried version 1.13.4 and it worked fine. So I'll close this for now since it's not an issue anymore.

**Comment by kirillzyusko** [comment]
@rarenatoe ah, glad newest version worked for you!

The reason behind the compatibility table is because Fabric may introduce some breaking changes, so I created this table when I was testing a particular version agains specific RN version.

But if newest version is fully compatible with RN 0.72 - that's good and you can use newest version! 🎉
