### ISSUE TITLE
Allow changing the `enabled` prop in `KeyboardProvider`

### ISSUE THREAD

**Issue by mozzius** [kirillzyusko/react-native-keyboard-controller#703]
Hey there!

We ran into an issue where enabling and disabling the Keyboard Controller via `useKeyboardController`  had unintended side effects - we had a screen, which turned it on, and then a dialog, which turned it on, but closing the dialog turned it off, which meant it was disabled for the screen. While technically this is user error, this pattern effectively requires setting state during a `useEffect` which is [strongly discouraged](https://react.dev/learn/you-might-not-need-an-effect#notifying-parent-components-about-state-changes) since it effectively breaks composition.

Instead, the source of truth about if it should be enabled should be lifted above the provider, but unfortunately `KeyboardProvider`'s `enabled` prop only allows setting this initial value. It would be great if it was possible to change this prop after the fact so that we can use a [ref counting approach](https://github.com/bluesky-social/social-app/pull/6727/files#diff-967b403e5301fe458eebe9e7670def2ab8a0b6144812c97bc12c8a4e8cdaa53c) instead. Ideally, this approach would be integrated into the package itself, but I understand that that gets more complicated since other apps might default to it being enabled and want to disable selectively. An alternative solution might be a "controlled" version and an "uncontrolled" version like `TextInput`.

Thanks for your consideration!

**Comment by kirillzyusko** [comment]
Thank you @mozzius for suggesting this feature!

I think at the moment I'm not ready to add it to the package - it was an intentional step to specify only initial value on provider level so that developers don't need to create their own context and make the code more complex.

What you are saying totally makes sense, but if we take a reference to the PR in BlueSky that you made - it's good showcase how the desired behavior can be achieved without breaking react rules (updating state in `useEffect`) and without patching the pacakge.

Though I agree with you that this additional code may not look perfect (all this additional management) - I added a possibility to fallback to default keyboard handling as a last resort, so ideally you shouldn't use this in your codebase too often 🙈 

I think we kind of reached a consensus in Discord/GitHub conversations, but if you still disagree - let me know and I'll re-open the issue.

**Comment by mozzius** [comment]
Yep, totally fine closing this following our discussion. Thank you!
