### ISSUE TITLE
Crash when modal gets shown 

### ISSUE THREAD

**Issue by exzos28** [kirillzyusko/react-native-keyboard-controller#735]
The issue is still valid.
The project has:
- react-native-keyboard-controller
- @gorhom/bottom-sheet

When I open a modal window I get a crash
`java.lang.RuntimeException: folly::toJson: JSON object value was an INF when serializing value at “progress”`

A bit of information from the debugger:
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/18f5a55e-1421-4906-a889-3eddecdd1ba1" />

- OS: android 10
- RN version: 0.76
- RN architecture: new, fabric
- JS engine: Hermes
- Library version: 1.15.0

**Additional context**
#718
#714

**Comment by exzos28** [comment]
progress is INF because of persistentKeyboardHeight, it's 0.0 
Do you really need a reproducible repository? Let me know if there's anything I can do to help here.

**Comment by exzos28** [comment]
Can we just check if it isn't infinity?

`progress = abs((height / persistentKeyboardHeight)).let { if (it.isNaN() || it.isInfinite()) 0.0 else it }`

**Comment by kirillzyusko** [comment]
> Do you really need a reproducible repository? 

Well, if you can prepare it that would be a dope!

> Can we just check if it is infinity?

We can and it will fix a crash, but I would like to use it only as a last resort. If we add that check we'll send `progress=0` and `height=45` (for example), which will add inconsistency - if you do `height`- based animations you will see that animation, 
 and if you use `progress`, then no 😔 🤷‍♂️ 

So my assumption is that we need to figure out why those insets changes are coming 🤔 Do you think it's doable to create a reproduction example?

**Comment by kirillzyusko** [comment]
Okay @exzos28 

I also see that a similar issue has been created in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/737

I feel a pain, when the app crashes, so I think it makes sense to add a dirty workaround with converting a value to `0` to avoid crash. It's better to have an incorrect animation for end user rather than a crash of the application 😔

**Comment by kirillzyusko** [comment]
I merged a fix - at least it should prevent a crash (but may lead to unexpected/inconsistent UI state: https://github.com/kirillzyusko/react-native-keyboard-controller/pull/740#issuecomment-2553315695

Let me know if you encounter any further issues. If you can prepare a reproduction example that would be a dope, since we can manage to discover a root problem and provide a fix 🤞
